# Generated by Django 3.1.7 on 2021-09-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0002_auto_20210920_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
